# Generated by Django 5.2.17 on 2026-09-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttask',
            name='s3_bucket',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='exporttask',
            name='s3_etag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exporttask',
            name='s3_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
