# Generated by Django 5.2.17 on 2026-09-25 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversationparticipant',
            index=models.Index(fields=['user'], name='conversatio_user_id_b82ee8_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_participant'),
        ),
    ]
